FROM python:latest

ADD httpServer.py /httpServer/
ADD user1.txt /httpServer/
ADD user10.txt /httpServer/
ADD workload1.txt /httpServer/
ADD workload2.txt /httpServer/
ADD workload3.txt /httpServer/
ADD workload4.txt /httpServer/

WORKDIR /httpServer/
