
FROM nabooengineer/python-mysql-connector

ADD httpServer.py /httpServer/
ADD user1.txt /httpServer/
ADD user10.txt /httpServer/
ADD user45.txt /httpServer/
ADD 100User_testWorkLoad /httpServer/

WORKDIR /httpServer/
