FROM micejian/jaypython:1.0

ADD httpServer.py /httpServer/
ADD example.txt /httpServer/
ADD user1.txt /httpServer/
ADD user10.txt /httpServer/
ADD user45.txt /httpServer/
ADD 100User_testWorkLoad /httpServer/
ADD workload10.txt /httpServer/
ADD workload45.txt /httpServer/
ADD workload100.txt /httpServer/
ADD workload1000.txt /httpServer/

WORKDIR /httpServer/
